name: Semgrep
on:
  push: 
    branches: [ master ]
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: checkout
      - uses: returntocorp/semgrep-action@v1
        name: run-semgrep
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: 88
          generateSarif: "1"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
        if: always()