name: ZAP-Test

on:
  push: 
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Python 3.7.10
        uses: actions/setup-python@v2
        with: 
          python-version: 3.7.10
      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Build Image
        run: docker build -t vulnerable-app .
      - name: Run Docker Container
        run: docker run -d -p 5050:5050 vulnerable-app
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://www.zaproxy.org/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
